from numpy import array
import numpy as np
from keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.text import Tokenizer
from sklearn.model_selection import train_test_split
import pandas as pd
import os
import re
import email
from os import makedirs
from keras.models import load_model
from numpy import dstack
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from keras.layers import Dropout
from nltk.tokenize import word_tokenize




dataInput=[
    ('Allen,', 'David.Allan@ENRON.com'),
    ('First of all, dress code is business casual (khakis etc.). My assistant,', 'David.Allan@ENRON.com'),
    ('Nyree Chanaba, will get back to you with particulars on the hotel. It', 'David.Allan@ENRON.com'),
    ('will probably be the Hyatt, which is kitty-corner from our office. But', 'David.Allan@ENRON.com'),
    ('whichever hotel it is, the concierge will be able to direct you to the', 'David.Allan@ENRON.com'),
    ('Enron Building: it\'s well-known, and we\'ll have you within 2-3 blocks of', 'David.Allan@ENRON.com'),
    ('our office at the most.', 'David.Allan@ENRON.com'),
    ('The morning session is for quiet conversations with anybody who wants', 'David.Allan@ENRON.com'),
    ('one-on-one time with you. At this point I don\'t know whether that will', 'David.Allan@ENRON.com'),
    ('be a lot of people or a few (we\'re in the middle of vacation time so', 'David.Allan@ENRON.com'),
    ('it\'s hard to predict attendance), but I would say 9 a.m. would be good.','David.Allan@ENRON.com'),
    ('Go to the lobby of the building and ask the security guards to call me', 'David.Allan@ENRON.com'),
    ('or Nyree (we\'re on the 29th floor).', 'David.Allan@ENRON.com'),
    ('If it\'s OK with you, why don\'t you pay your hotel bill and then fax me', 'David.Allan@ENRON.com'),
    ('the bill when you get home on Friday so we can cut a check.', 'David.Allan@ENRON.com'),
    ('If you\'re not too tired of Enron people at that time, I\'d like to take', 'David.Allan@ENRON.com'),
    ('you out to dinner on Thursday night.', 'David.Allan@ENRON.com'),
    ('As to the projector, we\'ll have something set up; in case the connection', 'David.Allan@ENRON.com'),
    ('doesn\'t work we also have laptops we can hook up.','David.Allan@ENRON.com'),
    ('We\'ll communicate more as the week goes on. We look forward to seeing', 'David.Allan@ENRON.com'),
    ('you!', 'David.Allan@ENRON.com'),
    ('Dave','David.Allan@ENRON.com'),

    ('We are in a loop.  We need a process to deal with this.  All ideas welcome.',  'kay.mann@enron.com'),
    ('I\'m looking for ISDA\'s between Enron MW and ENA and RMT.  I don\'t know where to look.  Can someone locate these for me?\nThanks,',   'kay.mann@enron.com'),
    ('Could I get a copy of the Midland Cogeneration Venture Limited Partnership termination letter? \n Thanks,',   'kay.mann@enron.com'),
    ('This is an internal draft, which has not been sent to CRRA, as far as I know. \n Kay',   'kay.mann@enron.com'),
    ('FYI.  I\'ll bring you the ONSI confidentiality agreement.',   'kay.mann@enron.com'),
    ('You try and see if he notices.',  'kay.mann@enron.com'),
    ('I would like to take Dec 26, 31 and Jan. 2 as vacation days.\n Thanks,\n Kay"',   'kay.mann@enron.com'),
    ('I\'m in the Enron Basics of Risk Management seminar Thurs (til 5) and Fri am.\nI would like to take next Wednesday as a day of vacation.\nThanks,\nKay"',  'kay.mann@enron.com'),
    ('I know there\'s a lot of anxiety about severance, reflecting the possibility that the existing Enron severance plan might be changed. I noticed in the merger',   'kay.mann@enron.com'),
    ('agreement that a ""floor"" was set on severance.  Have you heard anything about what Dynegy has for severance?',   'kay.mann@enron.com'),
    ('I know there are exceptions, but I was just curious, as lots of folks are very nervous.',   'kay.mann@enron.com'),
    ('From the merger agreement:',   'kay.mann@enron.com'),
    ('I can do that, especially if I get the list early in the day.',   'kay.mann@enron.com'),
    ('Jeff,\n What\'s your suggestion?  We are looking at a PA in connection with Tennessee Pipeline\'s open season. (did I get that right?)',   'kay.mann@enron.com'),
    ('Stephanie Panus has a few extra copies at her Desk.',   'kay.mann@enron.com'),
    ('At the very least, the cancellation charges are theirs.',   'kay.mann@enron.com'),
    ('Being revised currently, but lays out the deal:',   'kay.mann@enron.com'),

    ('Jim,\nThanks a lot. It is difficult to find a better example example of commitment', 'vince.kaminski@enron.com'),
    ('into Enron and to professional excellence\nthan  our weather guys.\n\nVince', 'vince.kaminski@enron.com'),
    ('We shall forward to you shortly a copy of the message from Sandeep with the\nnumbers you have ', 'vince.kaminski@enron.com'),
    ('requested.  What follows below are the extracts from two recent articles on', 'vince.kaminski@enron.com'),
    ('the power situation in India\npublished by The Financial Times.', 'vince.kaminski@enron.com'),
    ('The first article describes recent power outage in northern India affecting\nmillions of people.', 'vince.kaminski@enron.com'),
    ('One possible line of defense is pointing out to the value of  output lost due\nto  power', 'vince.kaminski@enron.com'),
    ('shortages. It is obvious that the value of lost production exceeds the cost\nof power produced', 'vince.kaminski@enron.com'),
    ('by the Dhabol plant (expensive as it may be). The power cut affected 230\nmillion people.', 'vince.kaminski@enron.com'),
    ('The second article is Enron specific.\nVince', 'vince.kaminski@enron.com'),
    ('Kim,\nFYI. I checked on the progress of the accounting adjustment and was told it would happen\nthis month.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI am forwarding you the notes from a regular weekly meeting with one of our\nsummer interns.', 'vince.kaminski@enron.com'),
    ('He works on review of the literature regarding drivers behind bid - offer\nspreads.', 'vince.kaminski@enron.com'),
    ('Please, let me know if you would like additional info.\n\nVince', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI scheduled a meeting with Norman Packard from the Prediction Company\nin Houston, July the 30th, 9:00 a.m.', 'vince.kaminski@enron.com'),
    ('Liz blocked out a few hours for the meeting.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nThis is the info  about the  WEBI program at Wharton\n\n.Vince', 'vince.kaminski@enron.com'),
    ('Any interest in this conference?\n\nhttp://www.haas.berkeley.edu/citm/conferences/010522/\n\n Vince', 'vince.kaminski@enron.com'),

    ('Since Congressman\'s Ose\'s been asking FERC alot of questons about what the ISO, DWR, etc. have been up to, perhaps he could write a ""Dear FERC"" letter saying',  'jeff.dasovich@enron.com'),
    ('""here\'s what I\'m hearing, it sounds serious and you need to investigate, pronto, and get back to me ASAP with your conclusions.""\n\nBest\nJeff',  'jeff.dasovich@enron.com'),
    ('Tim/Bob:\n\nAttached is the letter that we sent to Lynch explaining the info we thought ',  'jeff.dasovich@enron.com'),
    ('ought to be made publicly available.  We\'re discussing how we can ensure that ',  'jeff.dasovich@enron.com'),
    ('the market has access to any and all information that FERC might use in its',  'jeff.dasovich@enron.com'),
    ('""investigation"" so that independent analyses might be undertaken.  Is there',  'jeff.dasovich@enron.com'),
    ('anything in addition to the information we included in the letter to Lynch ',  'jeff.dasovich@enron.com'),
    ('(or that is already be publicly available) that FERC might use in its ',  'jeff.dasovich@enron.com'),
    ('investigation and that we ought to target for public release?  Thanks alot.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),
    ('FYI.  The report posted on the website fails to include the report\'s',  'jeff.dasovich@enron.com'),
    ('transmittal letter.  I just found that letter in the mail.  The letter ',  'jeff.dasovich@enron.com'),
    ('explains that the report\'s analysis DOES NOT include ""the events"" of May,',  'jeff.dasovich@enron.com'),
    ('June and July, which the Compliance unit is currently studying.  It will ',  'jeff.dasovich@enron.com'),
    ('release the results of that study in the Fall.',  'jeff.dasovich@enron.com'),
    ('Jennifer:\nI\'m on a call with Delainey that just got convened, which means that I might ',  'jeff.dasovich@enron.com'),
    ('be delayed till 11:45.  Unfortunately, Harry\'s on vacation.  I\'ll call in ',  'jeff.dasovich@enron.com'),
    ('just as soon as I get done with Delainey.  Also, I was on a call with Eric',  'jeff.dasovich@enron.com'),
    ('yesterday, during which I went over the S.D. legislation, so he should be',  'jeff.dasovich@enron.com'),
    ('fairly up to speed.  I\'ll get on just as soon as I can.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),

    ('"Traveling to have a business meeting takes the fun out of the trip.',  'phillip.allen@enron.com'),
    ('Especially if you have to prepare a presentation.',  'phillip.allen@enron.com'),
    ('I would suggest holding the business plan meetings here then take a trip without any formal business meetings.',  'phillip.allen@enron.com'),
    ('I would even try and get some honest opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about what is working and what is not.',  'phillip.allen@enron.com'),
    ('Too often the presenter speaks and the others are quiet just waiting for their turn.',  'phillip.allen@enron.com'),
    ('The meetings might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.',  'phillip.allen@enron.com'),
    ('Play golf and rent a ski boat and jet ski\'s.',  'phillip.allen@enron.com'),
    ('Flying somewhere takes too much time."',  'phillip.allen@enron.com'),
    ('Traveling to have a business meeting takes the fun out of the trip.  Especially if you have to prepare a presentation.  I would suggest',  'phillip.allen@enron.com'),
    ('holding the business plan meetings here then take a trip without any formal business meetings.  I would even try and get some honest',  'phillip.allen@enron.com'),
    ('opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about',  'phillip.allen@enron.com'),
    ('what is working and what is not.  Too often the presenter speaks and the others are quiet just waiting for their turn.   The meetings',  'phillip.allen@enron.com'),
    ('might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.  Play golf and rent a ski boat and jet ski\'s.  Flying somewhere takes too much time.',  'phillip.allen@enron.com'),


    ('"Congratulations to you as well Sally!  It is very encouraging to see a female Managing Director.', 'laura.scott@enron.com'),
    ('All the best.', 'laura.scott@enron.com'),

    ('"Dear Bill,', 'shona.wilson@enron.com' ),
    ('I am currently helping Milind Laad and Heidi Hellman establish a risk', 'shona.wilson@enron.com' ),
    ('operations department for the India trading company.', 'shona.wilson@enron.com') ,
    ('I was wondering if you would have 10 minutes to meet with me sometime this week to discuss how you', 'shona.wilson@enron.com' ),
    ('see India moving forward and in what time frame as this would help me a great', 'shona.wilson@enron.com'),
    ('deal in determining what types of systems, processes, and controls we should set up.', 'shona.wilson@enron.com'),
    ('Thanks,' 'shona.wilson@enron.com' ),
    ('Shona"', 'shona.wilson@enron.com' ),

    ('"To all',  'mike.jordan@enron.com,'),
    ('Tim has delivered the initial microsoft project plan for the MO integration - ',  'mike.jordan@enron.com'),
    ('this is available to all via the integration project \'office\' - i.e. Richard and Phil.',  'mike.jordan@enron.com'),

    ('"Please notate on your calendar:',   'cheryl.kuehl@enron.com'),
    ('The room location for the Associate PRC at the Hyatt will Arboretum 4 and 5',   'cheryl.kuehl@enron.com'),
    ('rather than Arboretum 1 and 2.',   'cheryl.kuehl@enron.com'),
    ('Thank you for your participation."',   'cheryl.kuehl@enron.com'),

    ('Corinne:', 'sara.shackleton@enron.com'),
    ('Attached is your arbitration language (marked) and our arbitration text.  I ', 'sara.shackleton@enron.com'),
    ('hope this does it!  Thanks.', 'sara.shackleton@enron.com'),
    ('This is a ""high volume"" trading counterparty.  Shouldn\'t we negotiate an ISDA', 'sara.shackleton@enron.com'),
    ('to replace the existing master?  SS"', 'sara.shackleton@enron.com'),

    ('Sara,',  'samon_corinne@jpmorgan.com'),
    ('Thank you for your fax.',  'samon_corinne@jpmorgan.com'),
    ('Section 180.3 of the CEA prohibits us from agreeing to any settlement',  'samon_corinne@jpmorgan.com'),
    ('procedure/forum ahead of time.  JPMFI, in accordance with 180.3, will offer 3',  'samon_corinne@jpmorgan.com'),
    ('forums - which will include AAA.  If Enron chooses AAA, the arbitration will',  'samon_corinne@jpmorgan.com'),
    ('be',  'samon_corinne@jpmorgan.com'),
    ('subject to the provisions specified in your fax dd 2/26/2001.',  'samon_corinne@jpmorgan.com'),
    ('Attached is JPM\'s proposed language for the arbitration agreement.',  'samon_corinne@jpmorgan.com'),
    ('(See attached file: ARBITRATION AGREEMENT.doc)',  'samon_corinne@jpmorgan.com'),
    ('If you are in agreement with the language, please forward Enron\'s proposed',  'samon_corinne@jpmorgan.com'),
    ('language (detailed in your 2/26 fax) electronically (if available).',  'samon_corinne@jpmorgan.com'),
    ('Thank you and Regards,',  'samon_corinne@jpmorgan.com'),
    ('Corinne',  'samon_corinne@jpmorgan.com'),

    ('We had 22 kids and 3 adult helpers.  The kids were pretty wild.  It wasn\'t one of our better days.  Oh well!', 'shelley.corman@enron.com'),
    ('If it\'s okay with you, I\'d like to take a week break next weekend.  I need to be at an event downtown at 1 Pm and it would be nice not ', 'shelley.corman@enron.com'),
    ('to rush.  I will bring you the boom box and CDs with music suggestions.  Would that be okay?', 'shelley.corman@enron.com'),
    ('Also, Stan is not available the third weekend in November so I have agreed to switch with him.  He will teach Nov 11 (I will be there', 'shelley.corman@enron.com'),
    ('to help)  and I will take Nov 18 (Kim promises that he will definitely be there).', 'shelley.corman@enron.com'),

    ('Hello Margaret,', 'monika.causholli@enron.com'),
    ('I don\'t know if you remember but I gave you my and my husband\'s passports to obtain H1b visas in Washington DC. You said that I have to ', 'monika.causholli@enron.com'),
    ('fill out a couple of forms before they were send out. Does that sound right to you or did I understand it wrong?', 'monika.causholli@enron.com'),
    ('Do you know how long it takes for the forms to be mailed? The reason I am asking this question is because I am afraid that the visa ', 'monika.causholli@enron.com'),
    ('process will be delayed and I have plans to travel in December. Without bothering you too much, can you explain to me the procedure.', 'monika.causholli@enron.com'),
    ('For example, Do I have to fill these two forms before the passports are mailed to DC or after. If I have to fill these forms before how', 'monika.causholli@enron.com'),
    (' can I speed up the process?', 'monika.causholli@enron.com'),
    ('thank you,', 'monika.causholli@enron.com'),
    ('Monika Causholli', 'monika.causholli@enron.com'),

    ('Hi, David,',  'aewhitman@mindspring.com',),
    ('A couple of questions:',  'aewhitman@mindspring.com'),
    ('dress code for visit',  'aewhitman@mindspring.com'),
    ('address and name of hotel.  My plane (DL 1857)is scheduled to arrive',  'aewhitman@mindspring.com'),
    ('at',  'aewhitman@mindspring.com'),
    ('1853.  I plan to go directly to the hotel.',  'aewhitman@mindspring.com'),
    ('do you want me to pay the bill and rebill you when I send the',  'aewhitman@mindspring.com'),
    ('invoice?',  'aewhitman@mindspring.com'),
    ('directions from the hotel to your office?  When do you want me to be',  'aewhitman@mindspring.com'),
    ('there on Thursday?',  'aewhitman@mindspring.com'),
    ('I plan to bring my laptop with several ppt presentations to show.  Do',  'aewhitman@mindspring.com'),
    ('you',  'aewhitman@mindspring.com'),
    ('have a hookup for the laptop to a projector?  I 	plan to leave a',  'aewhitman@mindspring.com'),
    ('copy of the',  'aewhitman@mindspring.com'),
    ('ppt slides with you if you have a zip file that can download them from',  'aewhitman@mindspring.com'),
    ('my',  'aewhitman@mindspring.com'),
    ('laptop.',  'aewhitman@mindspring.com'),
    ('I believe you were going to send me some info about Enron\'s plans and',  'aewhitman@mindspring.com'),
    ('objectives, now that I am on the team and have 	signed the',  'aewhitman@mindspring.com'),
    ('confidentiality',  'aewhitman@mindspring.com'),
    ('agreements.',  'aewhitman@mindspring.com'),
    ('any other questions I need to ask?',  'aewhitman@mindspring.com'),
    ('See you on Thursday.',  'aewhitman@mindspring.com'),
    ('Allen',  'aewhitman@mindspring.com'),

    ('Allen,', 'David.Allan@ENRON.com'),
    ('First of all, dress code is business casual (khakis etc.). My assistant,', 'David.Allan@ENRON.com'),
    ('Nyree Chanaba, will get back to you with particulars on the hotel. It', 'David.Allan@ENRON.com'),
    ('will probably be the Hyatt, which is kitty-corner from our office. But', 'David.Allan@ENRON.com'),
    ('whichever hotel it is, the concierge will be able to direct you to the', 'David.Allan@ENRON.com'),
    ('Enron Building: it\'s well-known, and we\'ll have you within 2-3 blocks of', 'David.Allan@ENRON.com'),
    ('our office at the most.', 'David.Allan@ENRON.com'),
    ('The morning session is for quiet conversations with anybody who wants', 'David.Allan@ENRON.com'),
    ('one-on-one time with you. At this point I don\'t know whether that will', 'David.Allan@ENRON.com'),
    ('be a lot of people or a few (we\'re in the middle of vacation time so', 'David.Allan@ENRON.com'),
    ('it\'s hard to predict attendance), but I would say 9 a.m. would be good.','David.Allan@ENRON.com'),
    ('Go to the lobby of the building and ask the security guards to call me', 'David.Allan@ENRON.com'),
    ('or Nyree (we\'re on the 29th floor).', 'David.Allan@ENRON.com'),
    ('If it\'s OK with you, why don\'t you pay your hotel bill and then fax me', 'David.Allan@ENRON.com'),
    ('the bill when you get home on Friday so we can cut a check.', 'David.Allan@ENRON.com'),
    ('If you\'re not too tired of Enron people at that time, I\'d like to take', 'David.Allan@ENRON.com'),
    ('you out to dinner on Thursday night.', 'David.Allan@ENRON.com'),
    ('As to the projector, we\'ll have something set up; in case the connection', 'David.Allan@ENRON.com'),
    ('doesn\'t work we also have laptops we can hook up.','David.Allan@ENRON.com'),
    ('We\'ll communicate more as the week goes on. We look forward to seeing', 'David.Allan@ENRON.com'),
    ('you!', 'David.Allan@ENRON.com'),
    ('Dave','David.Allan@ENRON.com'),

    ('We are in a loop.  We need a process to deal with this.  All ideas welcome.',  'kay.mann@enron.com'),
    ('I\'m looking for ISDA\'s between Enron MW and ENA and RMT.  I don\'t know where to look.  Can someone locate these for me?\nThanks,',   'kay.mann@enron.com'),
    ('Could I get a copy of the Midland Cogeneration Venture Limited Partnership termination letter? \n Thanks,',   'kay.mann@enron.com'),
    ('This is an internal draft, which has not been sent to CRRA, as far as I know. \n Kay',   'kay.mann@enron.com'),
    ('FYI.  I\'ll bring you the ONSI confidentiality agreement.',   'kay.mann@enron.com'),
    ('You try and see if he notices.',  'kay.mann@enron.com'),
    ('I would like to take Dec 26, 31 and Jan. 2 as vacation days.\n Thanks,\n Kay"',   'kay.mann@enron.com'),
    ('I\'m in the Enron Basics of Risk Management seminar Thurs (til 5) and Fri am.\nI would like to take next Wednesday as a day of vacation.\nThanks,\nKay"',  'kay.mann@enron.com'),
    ('I know there\'s a lot of anxiety about severance, reflecting the possibility that the existing Enron severance plan might be changed. I noticed in the merger',   'kay.mann@enron.com'),
    ('agreement that a ""floor"" was set on severance.  Have you heard anything about what Dynegy has for severance?',   'kay.mann@enron.com'),
    ('I know there are exceptions, but I was just curious, as lots of folks are very nervous.',   'kay.mann@enron.com'),
    ('From the merger agreement:',   'kay.mann@enron.com'),
    ('I can do that, especially if I get the list early in the day.',   'kay.mann@enron.com'),
    ('Jeff,\n What\'s your suggestion?  We are looking at a PA in connection with Tennessee Pipeline\'s open season. (did I get that right?)',   'kay.mann@enron.com'),
    ('Stephanie Panus has a few extra copies at her Desk.',   'kay.mann@enron.com'),
    ('At the very least, the cancellation charges are theirs.',   'kay.mann@enron.com'),
    ('Being revised currently, but lays out the deal:',   'kay.mann@enron.com'),

    ('Jim,\nThanks a lot. It is difficult to find a better example example of commitment', 'vince.kaminski@enron.com'),
    ('into Enron and to professional excellence\nthan  our weather guys.\n\nVince', 'vince.kaminski@enron.com'),
    ('We shall forward to you shortly a copy of the message from Sandeep with the\nnumbers you have ', 'vince.kaminski@enron.com'),
    ('requested.  What follows below are the extracts from two recent articles on', 'vince.kaminski@enron.com'),
    ('the power situation in India\npublished by The Financial Times.', 'vince.kaminski@enron.com'),
    ('The first article describes recent power outage in northern India affecting\nmillions of people.', 'vince.kaminski@enron.com'),
    ('One possible line of defense is pointing out to the value of  output lost due\nto  power', 'vince.kaminski@enron.com'),
    ('shortages. It is obvious that the value of lost production exceeds the cost\nof power produced', 'vince.kaminski@enron.com'),
    ('by the Dhabol plant (expensive as it may be). The power cut affected 230\nmillion people.', 'vince.kaminski@enron.com'),
    ('The second article is Enron specific.\nVince', 'vince.kaminski@enron.com'),
    ('Kim,\nFYI. I checked on the progress of the accounting adjustment and was told it would happen\nthis month.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI am forwarding you the notes from a regular weekly meeting with one of our\nsummer interns.', 'vince.kaminski@enron.com'),
    ('He works on review of the literature regarding drivers behind bid - offer\nspreads.', 'vince.kaminski@enron.com'),
    ('Please, let me know if you would like additional info.\n\nVince', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI scheduled a meeting with Norman Packard from the Prediction Company\nin Houston, July the 30th, 9:00 a.m.', 'vince.kaminski@enron.com'),
    ('Liz blocked out a few hours for the meeting.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nThis is the info  about the  WEBI program at Wharton\n\n.Vince', 'vince.kaminski@enron.com'),
    ('Any interest in this conference?\n\nhttp://www.haas.berkeley.edu/citm/conferences/010522/\n\n Vince', 'vince.kaminski@enron.com'),

    ('Since Congressman\'s Ose\'s been asking FERC alot of questons about what the ISO, DWR, etc. have been up to, perhaps he could write a ""Dear FERC"" letter saying',  'jeff.dasovich@enron.com'),
    ('""here\'s what I\'m hearing, it sounds serious and you need to investigate, pronto, and get back to me ASAP with your conclusions.""\n\nBest\nJeff',  'jeff.dasovich@enron.com'),
    ('Tim/Bob:\n\nAttached is the letter that we sent to Lynch explaining the info we thought ',  'jeff.dasovich@enron.com'),
    ('ought to be made publicly available.  We\'re discussing how we can ensure that ',  'jeff.dasovich@enron.com'),
    ('the market has access to any and all information that FERC might use in its',  'jeff.dasovich@enron.com'),
    ('""investigation"" so that independent analyses might be undertaken.  Is there',  'jeff.dasovich@enron.com'),
    ('anything in addition to the information we included in the letter to Lynch ',  'jeff.dasovich@enron.com'),
    ('(or that is already be publicly available) that FERC might use in its ',  'jeff.dasovich@enron.com'),
    ('investigation and that we ought to target for public release?  Thanks alot.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),
    ('FYI.  The report posted on the website fails to include the report\'s',  'jeff.dasovich@enron.com'),
    ('transmittal letter.  I just found that letter in the mail.  The letter ',  'jeff.dasovich@enron.com'),
    ('explains that the report\'s analysis DOES NOT include ""the events"" of May,',  'jeff.dasovich@enron.com'),
    ('June and July, which the Compliance unit is currently studying.  It will ',  'jeff.dasovich@enron.com'),
    ('release the results of that study in the Fall.',  'jeff.dasovich@enron.com'),
    ('Jennifer:\nI\'m on a call with Delainey that just got convened, which means that I might ',  'jeff.dasovich@enron.com'),
    ('be delayed till 11:45.  Unfortunately, Harry\'s on vacation.  I\'ll call in ',  'jeff.dasovich@enron.com'),
    ('just as soon as I get done with Delainey.  Also, I was on a call with Eric',  'jeff.dasovich@enron.com'),
    ('yesterday, during which I went over the S.D. legislation, so he should be',  'jeff.dasovich@enron.com'),
    ('fairly up to speed.  I\'ll get on just as soon as I can.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),

    ('"Traveling to have a business meeting takes the fun out of the trip.',  'phillip.allen@enron.com'),
    ('Especially if you have to prepare a presentation.',  'phillip.allen@enron.com'),
    ('I would suggest holding the business plan meetings here then take a trip without any formal business meetings.',  'phillip.allen@enron.com'),
    ('I would even try and get some honest opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about what is working and what is not.',  'phillip.allen@enron.com'),
    ('Too often the presenter speaks and the others are quiet just waiting for their turn.',  'phillip.allen@enron.com'),
    ('The meetings might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.',  'phillip.allen@enron.com'),
    ('Play golf and rent a ski boat and jet ski\'s.',  'phillip.allen@enron.com'),
    ('Flying somewhere takes too much time."',  'phillip.allen@enron.com'),
    ('Traveling to have a business meeting takes the fun out of the trip.  Especially if you have to prepare a presentation.  I would suggest',  'phillip.allen@enron.com'),
    ('holding the business plan meetings here then take a trip without any formal business meetings.  I would even try and get some honest',  'phillip.allen@enron.com'),
    ('opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about',  'phillip.allen@enron.com'),
    ('what is working and what is not.  Too often the presenter speaks and the others are quiet just waiting for their turn.   The meetings',  'phillip.allen@enron.com'),
    ('might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.  Play golf and rent a ski boat and jet ski\'s.  Flying somewhere takes too much time.',  'phillip.allen@enron.com'),


    ('"Congratulations to you as well Sally!  It is very encouraging to see a female Managing Director.', 'laura.scott@enron.com'),
    ('All the best.', 'laura.scott@enron.com'),

    ('"Dear Bill,', 'shona.wilson@enron.com' ),
    ('I am currently helping Milind Laad and Heidi Hellman establish a risk', 'shona.wilson@enron.com' ),
    ('operations department for the India trading company.', 'shona.wilson@enron.com') ,
    ('I was wondering if you would have 10 minutes to meet with me sometime this week to discuss how you', 'shona.wilson@enron.com' ),
    ('see India moving forward and in what time frame as this would help me a great', 'shona.wilson@enron.com'),
    ('deal in determining what types of systems, processes, and controls we should set up.', 'shona.wilson@enron.com'),
    ('Thanks,' 'shona.wilson@enron.com' ),
    ('Shona"', 'shona.wilson@enron.com' ),

    ('"To all',  'mike.jordan@enron.com,'),
    ('Tim has delivered the initial microsoft project plan for the MO integration - ',  'mike.jordan@enron.com'),
    ('this is available to all via the integration project \'office\' - i.e. Richard and Phil.',  'mike.jordan@enron.com'),

    ('"Please notate on your calendar:',   'cheryl.kuehl@enron.com'),
    ('The room location for the Associate PRC at the Hyatt will Arboretum 4 and 5',   'cheryl.kuehl@enron.com'),
    ('rather than Arboretum 1 and 2.',   'cheryl.kuehl@enron.com'),
    ('Thank you for your participation."',   'cheryl.kuehl@enron.com'),

    ('Corinne:', 'sara.shackleton@enron.com'),
    ('Attached is your arbitration language (marked) and our arbitration text.  I ', 'sara.shackleton@enron.com'),
    ('hope this does it!  Thanks.', 'sara.shackleton@enron.com'),
    ('This is a ""high volume"" trading counterparty.  Shouldn\'t we negotiate an ISDA', 'sara.shackleton@enron.com'),
    ('to replace the existing master?  SS"', 'sara.shackleton@enron.com'),

    ('Sara,',  'samon_corinne@jpmorgan.com'),
    ('Thank you for your fax.',  'samon_corinne@jpmorgan.com'),
    ('Section 180.3 of the CEA prohibits us from agreeing to any settlement',  'samon_corinne@jpmorgan.com'),
    ('procedure/forum ahead of time.  JPMFI, in accordance with 180.3, will offer 3',  'samon_corinne@jpmorgan.com'),
    ('forums - which will include AAA.  If Enron chooses AAA, the arbitration will',  'samon_corinne@jpmorgan.com'),
    ('be',  'samon_corinne@jpmorgan.com'),
    ('subject to the provisions specified in your fax dd 2/26/2001.',  'samon_corinne@jpmorgan.com'),
    ('Attached is JPM\'s proposed language for the arbitration agreement.',  'samon_corinne@jpmorgan.com'),
    ('(See attached file: ARBITRATION AGREEMENT.doc)',  'samon_corinne@jpmorgan.com'),
    ('If you are in agreement with the language, please forward Enron\'s proposed',  'samon_corinne@jpmorgan.com'),
    ('language (detailed in your 2/26 fax) electronically (if available).',  'samon_corinne@jpmorgan.com'),
    ('Thank you and Regards,',  'samon_corinne@jpmorgan.com'),
    ('Corinne',  'samon_corinne@jpmorgan.com'),

    ('We had 22 kids and 3 adult helpers.  The kids were pretty wild.  It wasn\'t one of our better days.  Oh well!', 'shelley.corman@enron.com'),
    ('If it\'s okay with you, I\'d like to take a week break next weekend.  I need to be at an event downtown at 1 Pm and it would be nice not ', 'shelley.corman@enron.com'),
    ('to rush.  I will bring you the boom box and CDs with music suggestions.  Would that be okay?', 'shelley.corman@enron.com'),
    ('Also, Stan is not available the third weekend in November so I have agreed to switch with him.  He will teach Nov 11 (I will be there', 'shelley.corman@enron.com'),
    ('to help)  and I will take Nov 18 (Kim promises that he will definitely be there).', 'shelley.corman@enron.com'),

    ('Hello Margaret,', 'monika.causholli@enron.com'),
    ('I don\'t know if you remember but I gave you my and my husband\'s passports to obtain H1b visas in Washington DC. You said that I have to ', 'monika.causholli@enron.com'),
    ('fill out a couple of forms before they were send out. Does that sound right to you or did I understand it wrong?', 'monika.causholli@enron.com'),
    ('Do you know how long it takes for the forms to be mailed? The reason I am asking this question is because I am afraid that the visa ', 'monika.causholli@enron.com'),
    ('process will be delayed and I have plans to travel in December. Without bothering you too much, can you explain to me the procedure.', 'monika.causholli@enron.com'),
    ('For example, Do I have to fill these two forms before the passports are mailed to DC or after. If I have to fill these forms before how', 'monika.causholli@enron.com'),
    (' can I speed up the process?', 'monika.causholli@enron.com'),
    ('thank you,', 'monika.causholli@enron.com'),
    ('Monika Causholli', 'monika.causholli@enron.com'),

    ('Hi, David,',  'aewhitman@mindspring.com',),
    ('A couple of questions:',  'aewhitman@mindspring.com'),
    ('dress code for visit',  'aewhitman@mindspring.com'),
    ('address and name of hotel.  My plane (DL 1857)is scheduled to arrive',  'aewhitman@mindspring.com'),
    ('at',  'aewhitman@mindspring.com'),
    ('1853.  I plan to go directly to the hotel.',  'aewhitman@mindspring.com'),
    ('do you want me to pay the bill and rebill you when I send the',  'aewhitman@mindspring.com'),
    ('invoice?',  'aewhitman@mindspring.com'),
    ('directions from the hotel to your office?  When do you want me to be',  'aewhitman@mindspring.com'),
    ('there on Thursday?',  'aewhitman@mindspring.com'),
    ('I plan to bring my laptop with several ppt presentations to show.  Do',  'aewhitman@mindspring.com'),
    ('you',  'aewhitman@mindspring.com'),
    ('have a hookup for the laptop to a projector?  I 	plan to leave a',  'aewhitman@mindspring.com'),
    ('copy of the',  'aewhitman@mindspring.com'),
    ('ppt slides with you if you have a zip file that can download them from',  'aewhitman@mindspring.com'),
    ('my',  'aewhitman@mindspring.com'),
    ('laptop.',  'aewhitman@mindspring.com'),
    ('I believe you were going to send me some info about Enron\'s plans and',  'aewhitman@mindspring.com'),
    ('objectives, now that I am on the team and have 	signed the',  'aewhitman@mindspring.com'),
    ('confidentiality',  'aewhitman@mindspring.com'),
    ('agreements.',  'aewhitman@mindspring.com'),
    ('any other questions I need to ask?',  'aewhitman@mindspring.com'),
    ('See you on Thursday.',  'aewhitman@mindspring.com'),
    ('Allen',  'aewhitman@mindspring.com'),

    ('Allen,', 'David.Allan@ENRON.com'),
    ('First of all, dress code is business casual (khakis etc.). My assistant,', 'David.Allan@ENRON.com'),
    ('Nyree Chanaba, will get back to you with particulars on the hotel. It', 'David.Allan@ENRON.com'),
    ('will probably be the Hyatt, which is kitty-corner from our office. But', 'David.Allan@ENRON.com'),
    ('whichever hotel it is, the concierge will be able to direct you to the', 'David.Allan@ENRON.com'),
    ('Enron Building: it\'s well-known, and we\'ll have you within 2-3 blocks of', 'David.Allan@ENRON.com'),
    ('our office at the most.', 'David.Allan@ENRON.com'),
    ('The morning session is for quiet conversations with anybody who wants', 'David.Allan@ENRON.com'),
    ('one-on-one time with you. At this point I don\'t know whether that will', 'David.Allan@ENRON.com'),
    ('be a lot of people or a few (we\'re in the middle of vacation time so', 'David.Allan@ENRON.com'),
    ('it\'s hard to predict attendance), but I would say 9 a.m. would be good.','David.Allan@ENRON.com'),
    ('Go to the lobby of the building and ask the security guards to call me', 'David.Allan@ENRON.com'),
    ('or Nyree (we\'re on the 29th floor).', 'David.Allan@ENRON.com'),
    ('If it\'s OK with you, why don\'t you pay your hotel bill and then fax me', 'David.Allan@ENRON.com'),
    ('the bill when you get home on Friday so we can cut a check.', 'David.Allan@ENRON.com'),
    ('If you\'re not too tired of Enron people at that time, I\'d like to take', 'David.Allan@ENRON.com'),
    ('you out to dinner on Thursday night.', 'David.Allan@ENRON.com'),
    ('As to the projector, we\'ll have something set up; in case the connection', 'David.Allan@ENRON.com'),
    ('doesn\'t work we also have laptops we can hook up.','David.Allan@ENRON.com'),
    ('We\'ll communicate more as the week goes on. We look forward to seeing', 'David.Allan@ENRON.com'),
    ('you!', 'David.Allan@ENRON.com'),
    ('Dave','David.Allan@ENRON.com'),

    ('We are in a loop.  We need a process to deal with this.  All ideas welcome.',  'kay.mann@enron.com'),
    ('I\'m looking for ISDA\'s between Enron MW and ENA and RMT.  I don\'t know where to look.  Can someone locate these for me?\nThanks,',   'kay.mann@enron.com'),
    ('Could I get a copy of the Midland Cogeneration Venture Limited Partnership termination letter? \n Thanks,',   'kay.mann@enron.com'),
    ('This is an internal draft, which has not been sent to CRRA, as far as I know. \n Kay',   'kay.mann@enron.com'),
    ('FYI.  I\'ll bring you the ONSI confidentiality agreement.',   'kay.mann@enron.com'),
    ('You try and see if he notices.',  'kay.mann@enron.com'),
    ('I would like to take Dec 26, 31 and Jan. 2 as vacation days.\n Thanks,\n Kay"',   'kay.mann@enron.com'),
    ('I\'m in the Enron Basics of Risk Management seminar Thurs (til 5) and Fri am.\nI would like to take next Wednesday as a day of vacation.\nThanks,\nKay"',  'kay.mann@enron.com'),
    ('I know there\'s a lot of anxiety about severance, reflecting the possibility that the existing Enron severance plan might be changed. I noticed in the merger',   'kay.mann@enron.com'),
    ('agreement that a ""floor"" was set on severance.  Have you heard anything about what Dynegy has for severance?',   'kay.mann@enron.com'),
    ('I know there are exceptions, but I was just curious, as lots of folks are very nervous.',   'kay.mann@enron.com'),
    ('From the merger agreement:',   'kay.mann@enron.com'),
    ('I can do that, especially if I get the list early in the day.',   'kay.mann@enron.com'),
    ('Jeff,\n What\'s your suggestion?  We are looking at a PA in connection with Tennessee Pipeline\'s open season. (did I get that right?)',   'kay.mann@enron.com'),
    ('Stephanie Panus has a few extra copies at her Desk.',   'kay.mann@enron.com'),
    ('At the very least, the cancellation charges are theirs.',   'kay.mann@enron.com'),
    ('Being revised currently, but lays out the deal:',   'kay.mann@enron.com'),

    ('Jim,\nThanks a lot. It is difficult to find a better example example of commitment', 'vince.kaminski@enron.com'),
    ('into Enron and to professional excellence\nthan  our weather guys.\n\nVince', 'vince.kaminski@enron.com'),
    ('We shall forward to you shortly a copy of the message from Sandeep with the\nnumbers you have ', 'vince.kaminski@enron.com'),
    ('requested.  What follows below are the extracts from two recent articles on', 'vince.kaminski@enron.com'),
    ('the power situation in India\npublished by The Financial Times.', 'vince.kaminski@enron.com'),
    ('The first article describes recent power outage in northern India affecting\nmillions of people.', 'vince.kaminski@enron.com'),
    ('One possible line of defense is pointing out to the value of  output lost due\nto  power', 'vince.kaminski@enron.com'),
    ('shortages. It is obvious that the value of lost production exceeds the cost\nof power produced', 'vince.kaminski@enron.com'),
    ('by the Dhabol plant (expensive as it may be). The power cut affected 230\nmillion people.', 'vince.kaminski@enron.com'),
    ('The second article is Enron specific.\nVince', 'vince.kaminski@enron.com'),
    ('Kim,\nFYI. I checked on the progress of the accounting adjustment and was told it would happen\nthis month.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI am forwarding you the notes from a regular weekly meeting with one of our\nsummer interns.', 'vince.kaminski@enron.com'),
    ('He works on review of the literature regarding drivers behind bid - offer\nspreads.', 'vince.kaminski@enron.com'),
    ('Please, let me know if you would like additional info.\n\nVince', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI scheduled a meeting with Norman Packard from the Prediction Company\nin Houston, July the 30th, 9:00 a.m.', 'vince.kaminski@enron.com'),
    ('Liz blocked out a few hours for the meeting.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nThis is the info  about the  WEBI program at Wharton\n\n.Vince', 'vince.kaminski@enron.com'),
    ('Any interest in this conference?\n\nhttp://www.haas.berkeley.edu/citm/conferences/010522/\n\n Vince', 'vince.kaminski@enron.com'),

    ('Since Congressman\'s Ose\'s been asking FERC alot of questons about what the ISO, DWR, etc. have been up to, perhaps he could write a ""Dear FERC"" letter saying',  'jeff.dasovich@enron.com'),
    ('""here\'s what I\'m hearing, it sounds serious and you need to investigate, pronto, and get back to me ASAP with your conclusions.""\n\nBest\nJeff',  'jeff.dasovich@enron.com'),
    ('Tim/Bob:\n\nAttached is the letter that we sent to Lynch explaining the info we thought ',  'jeff.dasovich@enron.com'),
    ('ought to be made publicly available.  We\'re discussing how we can ensure that ',  'jeff.dasovich@enron.com'),
    ('the market has access to any and all information that FERC might use in its',  'jeff.dasovich@enron.com'),
    ('""investigation"" so that independent analyses might be undertaken.  Is there',  'jeff.dasovich@enron.com'),
    ('anything in addition to the information we included in the letter to Lynch ',  'jeff.dasovich@enron.com'),
    ('(or that is already be publicly available) that FERC might use in its ',  'jeff.dasovich@enron.com'),
    ('investigation and that we ought to target for public release?  Thanks alot.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),
    ('FYI.  The report posted on the website fails to include the report\'s',  'jeff.dasovich@enron.com'),
    ('transmittal letter.  I just found that letter in the mail.  The letter ',  'jeff.dasovich@enron.com'),
    ('explains that the report\'s analysis DOES NOT include ""the events"" of May,',  'jeff.dasovich@enron.com'),
    ('June and July, which the Compliance unit is currently studying.  It will ',  'jeff.dasovich@enron.com'),
    ('release the results of that study in the Fall.',  'jeff.dasovich@enron.com'),
    ('Jennifer:\nI\'m on a call with Delainey that just got convened, which means that I might ',  'jeff.dasovich@enron.com'),
    ('be delayed till 11:45.  Unfortunately, Harry\'s on vacation.  I\'ll call in ',  'jeff.dasovich@enron.com'),
    ('just as soon as I get done with Delainey.  Also, I was on a call with Eric',  'jeff.dasovich@enron.com'),
    ('yesterday, during which I went over the S.D. legislation, so he should be',  'jeff.dasovich@enron.com'),
    ('fairly up to speed.  I\'ll get on just as soon as I can.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),

    ('"Traveling to have a business meeting takes the fun out of the trip.',  'phillip.allen@enron.com'),
    ('Especially if you have to prepare a presentation.',  'phillip.allen@enron.com'),
    ('I would suggest holding the business plan meetings here then take a trip without any formal business meetings.',  'phillip.allen@enron.com'),
    ('I would even try and get some honest opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about what is working and what is not.',  'phillip.allen@enron.com'),
    ('Too often the presenter speaks and the others are quiet just waiting for their turn.',  'phillip.allen@enron.com'),
    ('The meetings might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.',  'phillip.allen@enron.com'),
    ('Play golf and rent a ski boat and jet ski\'s.',  'phillip.allen@enron.com'),
    ('Flying somewhere takes too much time."',  'phillip.allen@enron.com'),
    ('Traveling to have a business meeting takes the fun out of the trip.  Especially if you have to prepare a presentation.  I would suggest',  'phillip.allen@enron.com'),
    ('holding the business plan meetings here then take a trip without any formal business meetings.  I would even try and get some honest',  'phillip.allen@enron.com'),
    ('opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about',  'phillip.allen@enron.com'),
    ('what is working and what is not.  Too often the presenter speaks and the others are quiet just waiting for their turn.   The meetings',  'phillip.allen@enron.com'),
    ('might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.  Play golf and rent a ski boat and jet ski\'s.  Flying somewhere takes too much time.',  'phillip.allen@enron.com'),


    ('"Congratulations to you as well Sally!  It is very encouraging to see a female Managing Director.', 'laura.scott@enron.com'),
    ('All the best.', 'laura.scott@enron.com'),

    ('"Dear Bill,', 'shona.wilson@enron.com' ),
    ('I am currently helping Milind Laad and Heidi Hellman establish a risk', 'shona.wilson@enron.com' ),
    ('operations department for the India trading company.', 'shona.wilson@enron.com') ,
    ('I was wondering if you would have 10 minutes to meet with me sometime this week to discuss how you', 'shona.wilson@enron.com' ),
    ('see India moving forward and in what time frame as this would help me a great', 'shona.wilson@enron.com'),
    ('deal in determining what types of systems, processes, and controls we should set up.', 'shona.wilson@enron.com'),
    ('Thanks,' 'shona.wilson@enron.com' ),
    ('Shona"', 'shona.wilson@enron.com' ),

    ('"To all',  'mike.jordan@enron.com,'),
    ('Tim has delivered the initial microsoft project plan for the MO integration - ',  'mike.jordan@enron.com'),
    ('this is available to all via the integration project \'office\' - i.e. Richard and Phil.',  'mike.jordan@enron.com'),

    ('"Please notate on your calendar:',   'cheryl.kuehl@enron.com'),
    ('The room location for the Associate PRC at the Hyatt will Arboretum 4 and 5',   'cheryl.kuehl@enron.com'),
    ('rather than Arboretum 1 and 2.',   'cheryl.kuehl@enron.com'),
    ('Thank you for your participation."',   'cheryl.kuehl@enron.com'),

    ('Corinne:', 'sara.shackleton@enron.com'),
    ('Attached is your arbitration language (marked) and our arbitration text.  I ', 'sara.shackleton@enron.com'),
    ('hope this does it!  Thanks.', 'sara.shackleton@enron.com'),
    ('This is a ""high volume"" trading counterparty.  Shouldn\'t we negotiate an ISDA', 'sara.shackleton@enron.com'),
    ('to replace the existing master?  SS"', 'sara.shackleton@enron.com'),

    ('Sara,',  'samon_corinne@jpmorgan.com'),
    ('Thank you for your fax.',  'samon_corinne@jpmorgan.com'),
    ('Section 180.3 of the CEA prohibits us from agreeing to any settlement',  'samon_corinne@jpmorgan.com'),
    ('procedure/forum ahead of time.  JPMFI, in accordance with 180.3, will offer 3',  'samon_corinne@jpmorgan.com'),
    ('forums - which will include AAA.  If Enron chooses AAA, the arbitration will',  'samon_corinne@jpmorgan.com'),
    ('be',  'samon_corinne@jpmorgan.com'),
    ('subject to the provisions specified in your fax dd 2/26/2001.',  'samon_corinne@jpmorgan.com'),
    ('Attached is JPM\'s proposed language for the arbitration agreement.',  'samon_corinne@jpmorgan.com'),
    ('(See attached file: ARBITRATION AGREEMENT.doc)',  'samon_corinne@jpmorgan.com'),
    ('If you are in agreement with the language, please forward Enron\'s proposed',  'samon_corinne@jpmorgan.com'),
    ('language (detailed in your 2/26 fax) electronically (if available).',  'samon_corinne@jpmorgan.com'),
    ('Thank you and Regards,',  'samon_corinne@jpmorgan.com'),
    ('Corinne',  'samon_corinne@jpmorgan.com'),

    ('We had 22 kids and 3 adult helpers.  The kids were pretty wild.  It wasn\'t one of our better days.  Oh well!', 'shelley.corman@enron.com'),
    ('If it\'s okay with you, I\'d like to take a week break next weekend.  I need to be at an event downtown at 1 Pm and it would be nice not ', 'shelley.corman@enron.com'),
    ('to rush.  I will bring you the boom box and CDs with music suggestions.  Would that be okay?', 'shelley.corman@enron.com'),
    ('Also, Stan is not available the third weekend in November so I have agreed to switch with him.  He will teach Nov 11 (I will be there', 'shelley.corman@enron.com'),
    ('to help)  and I will take Nov 18 (Kim promises that he will definitely be there).', 'shelley.corman@enron.com'),

    ('Hello Margaret,', 'monika.causholli@enron.com'),
    ('I don\'t know if you remember but I gave you my and my husband\'s passports to obtain H1b visas in Washington DC. You said that I have to ', 'monika.causholli@enron.com'),
    ('fill out a couple of forms before they were send out. Does that sound right to you or did I understand it wrong?', 'monika.causholli@enron.com'),
    ('Do you know how long it takes for the forms to be mailed? The reason I am asking this question is because I am afraid that the visa ', 'monika.causholli@enron.com'),
    ('process will be delayed and I have plans to travel in December. Without bothering you too much, can you explain to me the procedure.', 'monika.causholli@enron.com'),
    ('For example, Do I have to fill these two forms before the passports are mailed to DC or after. If I have to fill these forms before how', 'monika.causholli@enron.com'),
    (' can I speed up the process?', 'monika.causholli@enron.com'),
    ('thank you,', 'monika.causholli@enron.com'),
    ('Monika Causholli', 'monika.causholli@enron.com'),

    ('Hi, David,',  'aewhitman@mindspring.com',),
    ('A couple of questions:',  'aewhitman@mindspring.com'),
    ('dress code for visit',  'aewhitman@mindspring.com'),
    ('address and name of hotel.  My plane (DL 1857)is scheduled to arrive',  'aewhitman@mindspring.com'),
    ('at',  'aewhitman@mindspring.com'),
    ('1853.  I plan to go directly to the hotel.',  'aewhitman@mindspring.com'),
    ('do you want me to pay the bill and rebill you when I send the',  'aewhitman@mindspring.com'),
    ('invoice?',  'aewhitman@mindspring.com'),
    ('directions from the hotel to your office?  When do you want me to be',  'aewhitman@mindspring.com'),
    ('there on Thursday?',  'aewhitman@mindspring.com'),
    ('I plan to bring my laptop with several ppt presentations to show.  Do',  'aewhitman@mindspring.com'),
    ('you',  'aewhitman@mindspring.com'),
    ('have a hookup for the laptop to a projector?  I 	plan to leave a',  'aewhitman@mindspring.com'),
    ('copy of the',  'aewhitman@mindspring.com'),
    ('ppt slides with you if you have a zip file that can download them from',  'aewhitman@mindspring.com'),
    ('my',  'aewhitman@mindspring.com'),
    ('laptop.',  'aewhitman@mindspring.com'),
    ('I believe you were going to send me some info about Enron\'s plans and',  'aewhitman@mindspring.com'),
    ('objectives, now that I am on the team and have 	signed the',  'aewhitman@mindspring.com'),
    ('confidentiality',  'aewhitman@mindspring.com'),
    ('agreements.',  'aewhitman@mindspring.com'),
    ('any other questions I need to ask?',  'aewhitman@mindspring.com'),
    ('See you on Thursday.',  'aewhitman@mindspring.com'),
    ('Allen',  'aewhitman@mindspring.com'),

    ('Allen,', 'David.Allan@ENRON.com'),
    ('First of all, dress code is business casual (khakis etc.). My assistant,', 'David.Allan@ENRON.com'),
    ('Nyree Chanaba, will get back to you with particulars on the hotel. It', 'David.Allan@ENRON.com'),
    ('will probably be the Hyatt, which is kitty-corner from our office. But', 'David.Allan@ENRON.com'),
    ('whichever hotel it is, the concierge will be able to direct you to the', 'David.Allan@ENRON.com'),
    ('Enron Building: it\'s well-known, and we\'ll have you within 2-3 blocks of', 'David.Allan@ENRON.com'),
    ('our office at the most.', 'David.Allan@ENRON.com'),
    ('The morning session is for quiet conversations with anybody who wants', 'David.Allan@ENRON.com'),
    ('one-on-one time with you. At this point I don\'t know whether that will', 'David.Allan@ENRON.com'),
    ('be a lot of people or a few (we\'re in the middle of vacation time so', 'David.Allan@ENRON.com'),
    ('it\'s hard to predict attendance), but I would say 9 a.m. would be good.','David.Allan@ENRON.com'),
    ('Go to the lobby of the building and ask the security guards to call me', 'David.Allan@ENRON.com'),
    ('or Nyree (we\'re on the 29th floor).', 'David.Allan@ENRON.com'),
    ('If it\'s OK with you, why don\'t you pay your hotel bill and then fax me', 'David.Allan@ENRON.com'),
    ('the bill when you get home on Friday so we can cut a check.', 'David.Allan@ENRON.com'),
    ('If you\'re not too tired of Enron people at that time, I\'d like to take', 'David.Allan@ENRON.com'),
    ('you out to dinner on Thursday night.', 'David.Allan@ENRON.com'),
    ('As to the projector, we\'ll have something set up; in case the connection', 'David.Allan@ENRON.com'),
    ('doesn\'t work we also have laptops we can hook up.','David.Allan@ENRON.com'),
    ('We\'ll communicate more as the week goes on. We look forward to seeing', 'David.Allan@ENRON.com'),
    ('you!', 'David.Allan@ENRON.com'),
    ('Dave','David.Allan@ENRON.com'),

    ('We are in a loop.  We need a process to deal with this.  All ideas welcome.',  'kay.mann@enron.com'),
    ('I\'m looking for ISDA\'s between Enron MW and ENA and RMT.  I don\'t know where to look.  Can someone locate these for me?\nThanks,',   'kay.mann@enron.com'),
    ('Could I get a copy of the Midland Cogeneration Venture Limited Partnership termination letter? \n Thanks,',   'kay.mann@enron.com'),
    ('This is an internal draft, which has not been sent to CRRA, as far as I know. \n Kay',   'kay.mann@enron.com'),
    ('FYI.  I\'ll bring you the ONSI confidentiality agreement.',   'kay.mann@enron.com'),
    ('You try and see if he notices.',  'kay.mann@enron.com'),
    ('I would like to take Dec 26, 31 and Jan. 2 as vacation days.\n Thanks,\n Kay"',   'kay.mann@enron.com'),
    ('I\'m in the Enron Basics of Risk Management seminar Thurs (til 5) and Fri am.\nI would like to take next Wednesday as a day of vacation.\nThanks,\nKay"',  'kay.mann@enron.com'),
    ('I know there\'s a lot of anxiety about severance, reflecting the possibility that the existing Enron severance plan might be changed. I noticed in the merger',   'kay.mann@enron.com'),
    ('agreement that a ""floor"" was set on severance.  Have you heard anything about what Dynegy has for severance?',   'kay.mann@enron.com'),
    ('I know there are exceptions, but I was just curious, as lots of folks are very nervous.',   'kay.mann@enron.com'),
    ('From the merger agreement:',   'kay.mann@enron.com'),
    ('I can do that, especially if I get the list early in the day.',   'kay.mann@enron.com'),
    ('Jeff,\n What\'s your suggestion?  We are looking at a PA in connection with Tennessee Pipeline\'s open season. (did I get that right?)',   'kay.mann@enron.com'),
    ('Stephanie Panus has a few extra copies at her Desk.',   'kay.mann@enron.com'),
    ('At the very least, the cancellation charges are theirs.',   'kay.mann@enron.com'),
    ('Being revised currently, but lays out the deal:',   'kay.mann@enron.com'),

    ('Jim,\nThanks a lot. It is difficult to find a better example example of commitment', 'vince.kaminski@enron.com'),
    ('into Enron and to professional excellence\nthan  our weather guys.\n\nVince', 'vince.kaminski@enron.com'),
    ('We shall forward to you shortly a copy of the message from Sandeep with the\nnumbers you have ', 'vince.kaminski@enron.com'),
    ('requested.  What follows below are the extracts from two recent articles on', 'vince.kaminski@enron.com'),
    ('the power situation in India\npublished by The Financial Times.', 'vince.kaminski@enron.com'),
    ('The first article describes recent power outage in northern India affecting\nmillions of people.', 'vince.kaminski@enron.com'),
    ('One possible line of defense is pointing out to the value of  output lost due\nto  power', 'vince.kaminski@enron.com'),
    ('shortages. It is obvious that the value of lost production exceeds the cost\nof power produced', 'vince.kaminski@enron.com'),
    ('by the Dhabol plant (expensive as it may be). The power cut affected 230\nmillion people.', 'vince.kaminski@enron.com'),
    ('The second article is Enron specific.\nVince', 'vince.kaminski@enron.com'),
    ('Kim,\nFYI. I checked on the progress of the accounting adjustment and was told it would happen\nthis month.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI am forwarding you the notes from a regular weekly meeting with one of our\nsummer interns.', 'vince.kaminski@enron.com'),
    ('He works on review of the literature regarding drivers behind bid - offer\nspreads.', 'vince.kaminski@enron.com'),
    ('Please, let me know if you would like additional info.\n\nVince', 'vince.kaminski@enron.com'),
    ('Greg,\n\nI scheduled a meeting with Norman Packard from the Prediction Company\nin Houston, July the 30th, 9:00 a.m.', 'vince.kaminski@enron.com'),
    ('Liz blocked out a few hours for the meeting.\n\nVince"', 'vince.kaminski@enron.com'),
    ('Greg,\n\nThis is the info  about the  WEBI program at Wharton\n\n.Vince', 'vince.kaminski@enron.com'),
    ('Any interest in this conference?\n\nhttp://www.haas.berkeley.edu/citm/conferences/010522/\n\n Vince', 'vince.kaminski@enron.com'),

    ('Since Congressman\'s Ose\'s been asking FERC alot of questons about what the ISO, DWR, etc. have been up to, perhaps he could write a ""Dear FERC"" letter saying',  'jeff.dasovich@enron.com'),
    ('""here\'s what I\'m hearing, it sounds serious and you need to investigate, pronto, and get back to me ASAP with your conclusions.""\n\nBest\nJeff',  'jeff.dasovich@enron.com'),
    ('Tim/Bob:\n\nAttached is the letter that we sent to Lynch explaining the info we thought ',  'jeff.dasovich@enron.com'),
    ('ought to be made publicly available.  We\'re discussing how we can ensure that ',  'jeff.dasovich@enron.com'),
    ('the market has access to any and all information that FERC might use in its',  'jeff.dasovich@enron.com'),
    ('""investigation"" so that independent analyses might be undertaken.  Is there',  'jeff.dasovich@enron.com'),
    ('anything in addition to the information we included in the letter to Lynch ',  'jeff.dasovich@enron.com'),
    ('(or that is already be publicly available) that FERC might use in its ',  'jeff.dasovich@enron.com'),
    ('investigation and that we ought to target for public release?  Thanks alot.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),
    ('FYI.  The report posted on the website fails to include the report\'s',  'jeff.dasovich@enron.com'),
    ('transmittal letter.  I just found that letter in the mail.  The letter ',  'jeff.dasovich@enron.com'),
    ('explains that the report\'s analysis DOES NOT include ""the events"" of May,',  'jeff.dasovich@enron.com'),
    ('June and July, which the Compliance unit is currently studying.  It will ',  'jeff.dasovich@enron.com'),
    ('release the results of that study in the Fall.',  'jeff.dasovich@enron.com'),
    ('Jennifer:\nI\'m on a call with Delainey that just got convened, which means that I might ',  'jeff.dasovich@enron.com'),
    ('be delayed till 11:45.  Unfortunately, Harry\'s on vacation.  I\'ll call in ',  'jeff.dasovich@enron.com'),
    ('just as soon as I get done with Delainey.  Also, I was on a call with Eric',  'jeff.dasovich@enron.com'),
    ('yesterday, during which I went over the S.D. legislation, so he should be',  'jeff.dasovich@enron.com'),
    ('fairly up to speed.  I\'ll get on just as soon as I can.\n\nBest,\nJeff',  'jeff.dasovich@enron.com'),

    ('"Traveling to have a business meeting takes the fun out of the trip.',  'phillip.allen@enron.com'),
    ('Especially if you have to prepare a presentation.',  'phillip.allen@enron.com'),
    ('I would suggest holding the business plan meetings here then take a trip without any formal business meetings.',  'phillip.allen@enron.com'),
    ('I would even try and get some honest opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about what is working and what is not.',  'phillip.allen@enron.com'),
    ('Too often the presenter speaks and the others are quiet just waiting for their turn.',  'phillip.allen@enron.com'),
    ('The meetings might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.',  'phillip.allen@enron.com'),
    ('Play golf and rent a ski boat and jet ski\'s.',  'phillip.allen@enron.com'),
    ('Flying somewhere takes too much time."',  'phillip.allen@enron.com'),
    ('Traveling to have a business meeting takes the fun out of the trip.  Especially if you have to prepare a presentation.  I would suggest',  'phillip.allen@enron.com'),
    ('holding the business plan meetings here then take a trip without any formal business meetings.  I would even try and get some honest',  'phillip.allen@enron.com'),
    ('opinions on whether a trip is even desired or necessary.',  'phillip.allen@enron.com'),
    ('As far as the business meetings, I think it would be more productive to try and stimulate discussions across the different groups about',  'phillip.allen@enron.com'),
    ('what is working and what is not.  Too often the presenter speaks and the others are quiet just waiting for their turn.   The meetings',  'phillip.allen@enron.com'),
    ('might be better if held in a round table discussion format.',  'phillip.allen@enron.com'),
    ('My suggestion for where to go is Austin.  Play golf and rent a ski boat and jet ski\'s.  Flying somewhere takes too much time.',  'phillip.allen@enron.com'),


    ('"Congratulations to you as well Sally!  It is very encouraging to see a female Managing Director.', 'laura.scott@enron.com'),
    ('All the best.', 'laura.scott@enron.com'),

    ('"Dear Bill,', 'shona.wilson@enron.com' ),
    ('I am currently helping Milind Laad and Heidi Hellman establish a risk', 'shona.wilson@enron.com' ),
    ('operations department for the India trading company.', 'shona.wilson@enron.com') ,
    ('I was wondering if you would have 10 minutes to meet with me sometime this week to discuss how you', 'shona.wilson@enron.com' ),
    ('see India moving forward and in what time frame as this would help me a great', 'shona.wilson@enron.com'),
    ('deal in determining what types of systems, processes, and controls we should set up.', 'shona.wilson@enron.com'),
    ('Thanks,' 'shona.wilson@enron.com' ),
    ('Shona"', 'shona.wilson@enron.com' ),

    ('"To all',  'mike.jordan@enron.com,'),
    ('Tim has delivered the initial microsoft project plan for the MO integration - ',  'mike.jordan@enron.com'),
    ('this is available to all via the integration project \'office\' - i.e. Richard and Phil.',  'mike.jordan@enron.com'),

    ('"Please notate on your calendar:',   'cheryl.kuehl@enron.com'),
    ('The room location for the Associate PRC at the Hyatt will Arboretum 4 and 5',   'cheryl.kuehl@enron.com'),
    ('rather than Arboretum 1 and 2.',   'cheryl.kuehl@enron.com'),
    ('Thank you for your participation."',   'cheryl.kuehl@enron.com'),

    ('Corinne:', 'sara.shackleton@enron.com'),
    ('Attached is your arbitration language (marked) and our arbitration text.  I ', 'sara.shackleton@enron.com'),
    ('hope this does it!  Thanks.', 'sara.shackleton@enron.com'),
    ('This is a ""high volume"" trading counterparty.  Shouldn\'t we negotiate an ISDA', 'sara.shackleton@enron.com'),
    ('to replace the existing master?  SS"', 'sara.shackleton@enron.com'),

    ('Sara,',  'samon_corinne@jpmorgan.com'),
    ('Thank you for your fax.',  'samon_corinne@jpmorgan.com'),
    ('Section 180.3 of the CEA prohibits us from agreeing to any settlement',  'samon_corinne@jpmorgan.com'),
    ('procedure/forum ahead of time.  JPMFI, in accordance with 180.3, will offer 3',  'samon_corinne@jpmorgan.com'),
    ('forums - which will include AAA.  If Enron chooses AAA, the arbitration will',  'samon_corinne@jpmorgan.com'),
    ('be',  'samon_corinne@jpmorgan.com'),
    ('subject to the provisions specified in your fax dd 2/26/2001.',  'samon_corinne@jpmorgan.com'),
    ('Attached is JPM\'s proposed language for the arbitration agreement.',  'samon_corinne@jpmorgan.com'),
    ('(See attached file: ARBITRATION AGREEMENT.doc)',  'samon_corinne@jpmorgan.com'),
    ('If you are in agreement with the language, please forward Enron\'s proposed',  'samon_corinne@jpmorgan.com'),
    ('language (detailed in your 2/26 fax) electronically (if available).',  'samon_corinne@jpmorgan.com'),
    ('Thank you and Regards,',  'samon_corinne@jpmorgan.com'),
    ('Corinne',  'samon_corinne@jpmorgan.com'),

    ('We had 22 kids and 3 adult helpers.  The kids were pretty wild.  It wasn\'t one of our better days.  Oh well!', 'shelley.corman@enron.com'),
    ('If it\'s okay with you, I\'d like to take a week break next weekend.  I need to be at an event downtown at 1 Pm and it would be nice not ', 'shelley.corman@enron.com'),
    ('to rush.  I will bring you the boom box and CDs with music suggestions.  Would that be okay?', 'shelley.corman@enron.com'),
    ('Also, Stan is not available the third weekend in November so I have agreed to switch with him.  He will teach Nov 11 (I will be there', 'shelley.corman@enron.com'),
    ('to help)  and I will take Nov 18 (Kim promises that he will definitely be there).', 'shelley.corman@enron.com'),

    ('Hello Margaret,', 'monika.causholli@enron.com'),
    ('I don\'t know if you remember but I gave you my and my husband\'s passports to obtain H1b visas in Washington DC. You said that I have to ', 'monika.causholli@enron.com'),
    ('fill out a couple of forms before they were send out. Does that sound right to you or did I understand it wrong?', 'monika.causholli@enron.com'),
    ('Do you know how long it takes for the forms to be mailed? The reason I am asking this question is because I am afraid that the visa ', 'monika.causholli@enron.com'),
    ('process will be delayed and I have plans to travel in December. Without bothering you too much, can you explain to me the procedure.', 'monika.causholli@enron.com'),
    ('For example, Do I have to fill these two forms before the passports are mailed to DC or after. If I have to fill these forms before how', 'monika.causholli@enron.com'),
    (' can I speed up the process?', 'monika.causholli@enron.com'),
    ('thank you,', 'monika.causholli@enron.com'),
    ('Monika Causholli', 'monika.causholli@enron.com'),

    ('Hi, David,',  'aewhitman@mindspring.com',),
    ('A couple of questions:',  'aewhitman@mindspring.com'),
    ('dress code for visit',  'aewhitman@mindspring.com'),
    ('address and name of hotel.  My plane (DL 1857)is scheduled to arrive',  'aewhitman@mindspring.com'),
    ('at',  'aewhitman@mindspring.com'),
    ('1853.  I plan to go directly to the hotel.',  'aewhitman@mindspring.com'),
    ('do you want me to pay the bill and rebill you when I send the',  'aewhitman@mindspring.com'),
    ('invoice?',  'aewhitman@mindspring.com'),
    ('directions from the hotel to your office?  When do you want me to be',  'aewhitman@mindspring.com'),
    ('there on Thursday?',  'aewhitman@mindspring.com'),
    ('I plan to bring my laptop with several ppt presentations to show.  Do',  'aewhitman@mindspring.com'),
    ('you',  'aewhitman@mindspring.com'),
    ('have a hookup for the laptop to a projector?  I 	plan to leave a',  'aewhitman@mindspring.com'),
    ('copy of the',  'aewhitman@mindspring.com'),
    ('ppt slides with you if you have a zip file that can download them from',  'aewhitman@mindspring.com'),
    ('my',  'aewhitman@mindspring.com'),
    ('laptop.',  'aewhitman@mindspring.com'),
    ('I believe you were going to send me some info about Enron\'s plans and',  'aewhitman@mindspring.com'),
    ('objectives, now that I am on the team and have 	signed the',  'aewhitman@mindspring.com'),
    ('confidentiality',  'aewhitman@mindspring.com'),
    ('agreements.',  'aewhitman@mindspring.com'),
    ('any other questions I need to ask?',  'aewhitman@mindspring.com'),
    ('See you on Thursday.',  'aewhitman@mindspring.com'),
    ('Allen',  'aewhitman@mindspring.com'),
]




train_data = []
train_labels = []

for row in dataInput:
    train_data.append(row[0])
    train_labels.append(row[1])


#Tokenize the sentences
tokenizer = Tokenizer()
#preparing vocabulary
tokenizer.fit_on_texts(train_data)
#converting text into integer sequences
tokenised_email = tokenizer.texts_to_sequences(train_data)
#print(tokenised_email)

voc_size = len(tokenizer.word_index) + 1 #+1 for padding
#print("check the voc size: ", voc_size)

X = pad_sequences(tokenised_email, maxlen=30, padding='post')
print(X.shape)

y = tokenizer.texts_to_matrix(train_labels)
print(y.shape)

trainX, testX, trainy, testy = train_test_split(X, y, test_size=0.37, train_size=0.63, random_state=42)
#print(trainX.shape, trainy.shape)


dim = 30
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=30))
#model.add(Flatten(input_shape=[38]))
#model.add(Dense(200, activation="relu"))
#model.add(Dense(200, activation="relu"))
#model.add(Dense(100, activation="relu"))
#model2.add(Dropout(rate=0.4))
model.add(Flatten())
model.add(Dense(725, activation='softmax'))
# compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
# summarize the model
print(model.summary())
# fit the model
histtory = model.fit(trainX, trainy, validation_data=(testX, testy), epochs=10, verbose=1)
# evaluate the model
# evaluate the model
_, train_acc = model.evaluate(trainX, trainy, verbose=0)
_, test_acc = model.evaluate(testX, testy, verbose=0)
print('Train: %.3f, Test: %.3f' % (train_acc, test_acc))